# Generated by Django 3.1 on 2020-10-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
