# Generated by Django 3.1 on 2020-10-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_remove_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-updated',)},
        ),
    ]
