# Generated by Django 3.1 on 2020-10-13 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_auto_20201013_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('updated',)},
        ),
    ]
