# Generated by Django 3.1 on 2020-10-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_auto_20201013_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
