# Generated by Django 3.1 on 2020-10-13 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20201012_1417'),
        ('Posts', '0007_auto_20201013_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('by_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kisne_comment_kia', to='Profile.person')),
                ('on_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_ka_batao', to='Posts.post')),
            ],
        ),
    ]
