# Generated by Django 3.1 on 2020-10-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0009_auto_20201015_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-updated',)},
        ),
    ]
