# Generated by Django 3.1 on 2020-10-14 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0003_auto_20201012_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following_in_model', to=settings.AUTH_USER_MODEL),
        ),
    ]
